### ISSUE TITLE
read_muxed_data() doesn't return the expected data in version 2.8.2

### ISSUE THREAD

**Issue by cenkoloji** [D-TACQ/acq400_hapi#117]
Hello @petermilne  and all, 

I'm trying to retrieve data/timestamps from a non-demuxed d-tacq. Using the method acq400.read_muxed_data(), I get correct results on version 2.3.4, but not on version 2.8.2 (unless I misunderstand what this method should do)

I tracked it down to following lines: https://github.com/D-TACQ/acq400_hapi/blob/98765e41082a07713452d12afd81ab422d58a8c7/acq400_hapi/acq400.py#L593-L596

And specifically: 
```python
            data = data[:,np.array(channels)-1].transpose()
```

channels is ```(0)```, so this line returns a numpy array with ```shape=(N,)``` where N is the number of samples (PRE+POST). Do I misunderstand what this method should do?

**Comment by petermilne** [comment]
Hi Cenk

Thank you for the comment. I'm not sure how "it worked" on 2.3.4 because the older version would not handle non-demux (raw) data at all.
commit 49bcaf4631ea842bd93c0745f00498d27155dadf
Author: Sean <sean.alsop@d-tacq.co.uk>
Date:   Thu Oct 1 11:10:26 2020 +0100

    Added a way to pull muxed data from port 53000 and demux.
            modified:   acq400_hapi/acq400.py


The change looks reasonable. Can you be more explicit about what is going wrong?.

A mockup suggests it's doing the right thing:
channels=list(range(1,64+1))
data=np.linspace(0, 64000, num=64000)
data=data.reshape(-1,64)
data
>>> data
array([[0.00000000e+00, 1.00001563e+00, 2.00003125e+00, ...,
        6.10009531e+01, 6.20009688e+01, 6.30009844e+01],
       [6.40010000e+01, 6.50010156e+01, 6.60010313e+01, ...,
        1.25001953e+02, 1.26001969e+02, 1.27001984e+02],
       ...,
       [6.39369990e+04, 6.39379990e+04, 6.39389990e+04, ...,
        6.39980000e+04, 6.39990000e+04, 6.40000000e+04]])


>>> data2=data[:,np.array(channels)-1].transpose()
>>> data2
array([[0.00000000e+00, 6.40010000e+01, 1.28002000e+02, ...,
        6.38089970e+04, 6.38729980e+04, 6.39369990e+04],
       [1.00001563e+00, 6.50010156e+01, 1.29002016e+02, ...,
        6.38099970e+04, 6.38739980e+04, 6.39379990e+04],

(first channel steps in steps of 64 ..)

>>> data2.shape
(64, 1000)

That's probably the opposite of your comment, ie
NOT shape=(NSAM,)  but shape=(NCHAN,)

ie: numpy is doing the demux for us, we're no longer looking at raw (multiplexed) data.

If you want to see real raw data, maybe uut.read_chan(0, NCHAN*NSAM) will be what you would want

**Comment by cenkoloji** [comment]
> I'm not sure how "it worked" on 2.3.4 because the older version would not handle non-demux (raw) data at all.

I see. Thanks.

I still thing there is an issue. ```read_muxed_data()``` calls

https://github.com/D-TACQ/acq400_hapi/blob/98765e41082a07713452d12afd81ab422d58a8c7/acq400_hapi/acq400.py#L1006

Which means in your example, you'd have `channels=(0)`
```python
data=np.linspace(0, 64000, num=64000)

channels=(0)
data = data.reshape((-1, 64)) # All good until here, next line is the problem

data = data[:,np.array(channels)-1].transpose()
data.shape   # Returns (1000,)
```

I think the `read_muxed_data()` should do something like:

```python
self.read_channels(list(range(1,int(self.s0.NCHAN)+1)), -1)
``` 

> If you want to see real raw data, maybe uut.read_chan(0, NCHAN*NSAM) will be what you would want

Indeed, for now that's what I use, (specifically `uut.read_chan(0,-1)`)

**Comment by petermilne** [comment]
Hello Cenk

Thanks for the update. I was wrong to say the original version would not handle raw data at all, actually, for channel=0, non-demuxed data, it would have just passed it straight through, which is probably what a client would want.

So, for "raw" data your code call uut.read_channels((0)), and this reads "channel 0", returning raw data, ie 
all the channels in raw data[sample][channel] order

But the changed call means that this returns data that is locally demuxed. 
ie data[channel][sample] order ..

So the API call returns very different data for the same input. Actually, this is bad. Sorry, and I think this was what prompted you to raise the issue. It's bad, because we should never change published behaviour, breaking existing code.

Further, if the ACQ has DEMUX=0, but the call is with a list of non-zero channels, I think this code is intended to demux and return those channels locally. This is good .. assuming it works.

I think I'm going to change this again, to restore the original behaviour, then add a boolean optional arg localdemux=False, if set true it will do the local demuxing as intended by Sean.

**Comment by petermilne** [comment]
Hello Cenk ... please take a look at 2.9.0, I think this restores the original behaviour and adds the local demux feature 
please see detail comment and test program at:
https://github.com/D-TACQ/acq400_hapi/commit/9875d0c847f011098e93692456d2171950058f04

The test program used a delta-sigma ADC (ACQ435). This has a useful channel-id feature. I think we can get a similar result with a SAR converter, enable simulate=1, this puts a numerical ramp in the data. If the data presents as a ramp with step==1, then this is "raw" data, if the step==NCHAN, then it's channelized data.

**Comment by cenkoloji** [comment]
Thanks a lot Peter, I tested it with a d-tacq now, it works as expected.

**Comment by cenkoloji** [comment]
Oh in fact I forgot to mention, while testing I had to remove the following line, as it breaks the import

https://github.com/D-TACQ/acq400_hapi/blob/cdb3fd438c84cd4d87061edeedd9f7e76a0e85f9/acq400_hapi/__init__.py#L19
```
>>> import acq400_hapi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "acq400_hapi/__init__.py", line 19, in <module>
    from .utils import timing
ImportError: No module named utils
```

**Comment by petermilne** [comment]
Missing file acq400_hapi/utils.py, added at 9977a51
Thanks for the heads-up.
