### ISSUE TITLE
A querry does not return if the answer is empy

### ISSUE THREAD

**Issue by zack-vii** [D-TACQ/acq400_hapi#94]
```
uut = Acq400(ip)
uut.s0.state
```
usually returns something like  "0 0 0 0 0".
Lacking a better way of detecting the arm,ed state when arming using a socket connection to 4210, I polled state. but state sometime returns an empty string which locks up the api.

```
  File "/usr/local/mdsplus/python/acq400_hapi/netclient.py", line 48, in receive_message
    self.buffer += self.sock.recv(maxlen).decode("latin-1")
```

**Comment by petermilne** [comment]
Hi Timo

Nice feedback from github, thank you, keep it coming ..

(Does Timo Schroeder <notifications@github.com> work for you?.
I'm kind of thinking not).

Could we persuade you NOT to poll the state?.
Because the harder you poll it, the more likely it is to fail.

There's an event driven method that works much better.
/acq400.py   StatusMonitor.

     def state(self):
         return self.statmon.status[SF.STATE]

ie: use uut.state() in preference to uut.s0.state

(in the former, your code polls a local variable is event driven from a dedicated thread and socket, the later sends out a poll to a remote value .. that's frequently updated, if you catch it during the update, it's probably undefined).


Best regards


Peter.

On 22/06/2020 22:23, Timo Schroeder wrote:
> ```
> uut = Acq400(ip)
> uut.s0.state
> ```
> usually returns something like  "0 0 0 0 0".
> Lacking a better way of detecting the arm,ed state when arming using a socket connection to 4210, I polled state. but state sometime returns an empty string which locks up the api.
> 
> ```
>    File "/usr/local/mdsplus/python/acq400_hapi/netclient.py", line 48, in receive_message
>      self.buffer += self.sock.recv(maxlen).decode("latin-1")
> ```
> 


-- 
Peter Milne
Director of Sales
www.d-tacq.com

**Comment by zack-vii** [comment]
well Timo Schroeder <notifications@github.com> is just because i did something on github as me and github notified you. hence the github email. but yes thats me. 

You sure can persuade me to use a different approach. But I had to realize that the statmon did not catch the state change when triggered by openning a connection to the stream port.

Some further analysis showed that state returns '' during the arm procedure (clock sync stuff).

**Comment by petermilne** [comment]
STREAM and TRANSIENT are DIFFERENT.  STREAM STATE and TRANSIENT STATE are recorded differently;
they maybe combined to some extent, but not really successfully.

For detecting STREAM STATE correctly, please use:

PV : ${uut}:MODE:CONTINUOUS:STATE

local knob: get.site 0 CONTINUOUS:STATE

HAPI
uut.s0.CONTINUOUS_STATE

acq1001_417> get.site 0 CONTINUOUS:STATE
CONTINUOUS:STATE RUN

**Comment by zack-vii** [comment]
Well, i noticed.. it would be great though it the state monitor would catch the STREAM state. it doe if you do "streamtonowhere start" but it does not if you start the stream with the port. so i was wondering if one could add that

**Comment by petermilne** [comment]
The STATE MONITOR is really the TRANSIENT STATE MONITOR! 
The service at port 2235 is connected directly to "faultmon", that is the thing that runs transients.
If we were to intercept that, it's likely to cause breakage.
Clue is in HAPI:      TSTAT = 2235
"TSTAT" : transient status.

Did I suggest this to you in the first place?. Sorry, my bad call. It's really good for TRANSIENT, but isn't suitable for STREAM.
